### ISSUE TITLE
Is there any place to leave donations ?

### ISSUE THREAD

**Issue by jweinst1** [drj11/pypng#107]
Absolutely love this project! It works great for making the fundamental PNG color types and is a great tool to use in Python.

Is there any where donations can be left to support the maintaining and future of the project ?

**Comment by drj11** [comment]
That is very encouraging to hear, and a very kind thing to say, thanks!

At the moment I am employed and financially secure, it would be inappropriate to seek donations. Even if you could donate money, it wouldn't be used to support and maintain the project.

However, I'm not opposed to the idea that one to donate to a fund which could occasionally be used to pay someone to make change, or to pass on donations to other charitable causes.

If you were to contribute money to a project, how would you normally expect to do that?

If you still want to donate, can I instead suggest that give money to the Python Software Foundation, or if you are already a member, find a group helping under-represented groups in coding.

Cheers,
 drj

**Comment by jweinst1** [comment]
GitHub now supports a sponsorship option for repositories to help you add a sponsorship button. But I respect your view on this, its understandable :) 

The PSF foundation is a great idea as well, thanks.
