### ISSUE TITLE
how to export produced .png on custom other path ?

### ISSUE THREAD

**Issue by deepanshu-nickelfox** [drj11/pypng#110]

**Comment by drj11** [comment]
what have you tried so far?

**Comment by deepanshu-nickelfox** [comment]
so you don't know either @drj11 , dammn

**Comment by drj11** [comment]
it's more that you're initial question was incredibly vague and gives no one any indication of how to proceed. There are many ways to use PyPNG to do many different things. If you could provide more specific detail on what you're trying to achieve then commenters on this thread might be able to help.

**Comment by deepanshu-nickelfox** [comment]
Sir, My question was, whenever a new QrCode Generated it produced in same path where my code file is present.
But, now i want a custom path ie. some    `desktop/Mypc/Myqrfolder`

how can i do that??

**Comment by drj11** [comment]
if you using `image.save("path.png")` then put the full path in: `image.save("/home/drj/Desktop/path.png")`
