### ISSUE TITLE
write from iterator

### ISSUE THREAD

**Issue by nschloe** [drj11/pypng#117]
I have an iterator `RowIterator` that returns the values for the `next()` row of the output PNG. I would like to use this iterator to write a file, e.g.,
```python
# [...]

iterator = RowIterator(A, border_width, border_color, colormap)

w = png.Writer(
    n, m,
    greyscale=iterator.mode != "rgb",
    bitdepth=iterator.bitdepth,
)

with open(filename, "wb") as f:
    w.write(f, iterator)
```
First creating the full data array is not an option -- it's too large.

**Comment by drj11** [comment]
It is in fact supposed to work with iterators (at least, when it can), so i'll have a look.

Do you happen to have a more specific example that fails?

**Comment by nschloe** [comment]
You're right, it does actually work out of the box! Using this in [matplotx](https://github.com/nschloe/matplotx#spy-plots-betterspy) now. Thanks for making this!

**Comment by drj11** [comment]
great! If you think the documentation could be improved or made clearer, let me know.
