### ISSUE TITLE
TypeError: object of type 'int' has no len()

### ISSUE THREAD

**Issue by SuperArcherG** [drj11/pypng#120]
I don't understand what I'm doing wrong, could someone please help?
I cant tell if this is a me issue or an issue with PyPNG.
I'm simply trying to generate an image 372px by 128px with a random color for each pixel.
I cant find any documentation on this on the docs.

Code:
```Python
import random
import png
screenTileSize = (372, 128)
col = [0] * screenTileSize[0] * 3
wid = [col] * screenTileSize[1]

for x in range(screenTileSize[0]):
    for y in range(screenTileSize[1]):
        wid[y][x] = random.randint(0, 255)


png.from_array(col, 'RGB').save("BG.png")
```

Error Log:
```Shell
Traceback (most recent call last):
  File "/Users/USERNAME/Desktop/Whispers-in-the-Mist/Scripts/Util/MakeImageFromMap.py", line 12, in <module>
    png.from_array(col, 'RGB').save("BG.png")
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/png.py", line 1235, in from_array
    width = len(row) // planes
TypeError: object of type 'int' has no len()```

**Comment by ssieb** [comment]
I don't know about the error, but `wid = [col] * screenTileSize[1]` does not do what you think it does.  Every row has the exact same content.

**Comment by drj11** [comment]
PyPNG has moved to https://gitlab.com/drj11/pypng and i'm archiving this repo.

I didn't notice this issue at the time, but it's still useful for some feedback:

@ssieb is correct that every row has the same content. The 2D array you make and assign to wid, has the right numbers of rows, but each row is a reference to _the same list object_. Therefore, your later loop that assigns pixels continually overwrites that same row object and only the last iteration writes values that gets used.

That, however, should not stop PyPNG from working.

The bug that is responsible for the immediate error that you report is a simple typo: in the last line `col` should be `wid`:

    png.from_array(wid, 'RGB').save("BG.png")

I would normally call `wid` `rows` as it is a sequence of rows.

That produces the following image:

![image](https://user-images.githubusercontent.com/1215412/231428324-b345f0cd-9775-40eb-87d7-949980fc816f.png)

You make an image 372 pixels wide, but only write the first 128 pixels of each row. There may be some confusion over pixels and values here. A row (in an RGB image) should have 3 values per pixel. I note that 372 = 3 * 128. Are you trying to create a 128x128 _pixel_ image? (which would have 372 values per row).

It's a nice example idea, i may add it or something similar.
