### ISSUE TITLE
Documentaton, missing note

### ISSUE THREAD

**Issue by darbula** [drj11/pypng#20]
In docs [here](http://pythonhosted.org/pypng/png.html#png.from_array) there is a note missing:

    The use of the term *3-dimensional* is for marketing purposes
    only.  It doesn't actually work.  Please bear with us.  Meanwhile
    enjoy the complimentary snacks (on request) and please use a
    2-dimensional array.

**Comment by drj11** [comment]
Turns out it was a missing `:`. But the note is irrelevant now. Since 3D works.
