### ISSUE TITLE
Document Reader metadata a bit?

### ISSUE THREAD

**Issue by techtonik** [drj11/pypng#3]
While pypng is nice to play with, it would be nice if Reader().preamble() doc pointed to metadata descrpition and metadata description mentioned that it is not available in reader oject until preamble is called. Is it worth it?

**Comment by drj11** [comment]
That's all a bit internal, but if you submitted a clean patch that improves the documentation, i'd probably accept it.

**Comment by techtonik** [comment]
That could be fun, but I am not sure there will be time to get back to hacking on PNGs.
