### ISSUE TITLE
Documentation for pngReader.read doesn't identify return 4-tuple item names

### ISSUE THREAD

**Issue by thorsummoner** [drj11/pypng#56]
Mostly this is an issue I had distinguishing whether the first two variables of the four-tuple were width, or height.

**Comment by drj11** [comment]
Yeah it should return a namedtuple. I like that.

It is slightly clearer to get the width and height out of the info dict.

**Comment by thorsummoner** [comment]
I was able to extract the key order out of the source code documentation. is the examples on pythonhosted that I nag about

**Comment by drj11** [comment]
Oh yeah, sorry. You did actually say documentation in the issue title.

Which example in particular?

**Comment by thorsummoner** [comment]
https://pythonhosted.org/pypng/ex.html#reading the section on reading :D
and thanks for this awesome tool, I've used it to read .ora files too

**Comment by drj11** [comment]
Oh yes, that does seem unclear. Thanks for pointing it out!

**Comment by drj11** [comment]
Clairifed in ba68cf79cbd0f24df8f4aac52c1c777e0e774f4e which will eventually find it's way into a release.
