### ISSUE TITLE
UnicodeDecodeError on read

### ISSUE THREAD

**Issue by nikolas** [drj11/pypng#57]
Reading a png file with python 3.4.3, pypng 0.0.18 I get this error:
```
  File "/home/nik/src/t1m1/scene/font.py", line 9, in __init__
    print(r.read())
  File "/home/nik/src/t1m1/venv/lib/python3.4/site-packages/png.py", line 1950, in read
    self.preamble(lenient=lenient)
  File "/home/nik/src/t1m1/venv/lib/python3.4/site-packages/png.py", line 1740, in preamble
    self.validate_signature()
  File "/home/nik/src/t1m1/venv/lib/python3.4/site-packages/png.py", line 1725, in validate_signature
    self.signature = self.file.read(8)
  File "/home/nik/.pyenv/versions/3.4.3/lib/python3.4/codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```

Here's the png file:
![font8x12](https://cloud.githubusercontent.com/assets/59292/9923158/88711e30-5cbf-11e5-8812-2e797aef18b7.png)

**Comment by drj11** [comment]
I think I'll need to see how you open the file and create the `Reader` instance. Can you paste or link to your `font.py` file please?

PS Nice PNG. Is that the 8-bit Amstrad font?

**Comment by nikolas** [comment]
Here's all I had in my font.py file:

```py
import png


class Font():
    def __init__(self):
        filename = 'scene/font8x12.png'
        with open(filename, 'r') as f:
            r = png.Reader(file=f)
            print(r.read())
```

The PNG I got from here: http://www.piclist.com/techref/datafile/charset/extractor/charset_extractor.htm

**Comment by drj11** [comment]
in general PNG files need to be opened in binary mode. So on instead of `open(filename, 'r')` you need `open(filename, 'rb')`.

Certainly this could be made more clear in the docs, and possibly PyPNG should check for this case more explicitly.

**Comment by nikolas** [comment]
Oh duh.. should've figured this was a mistake on my part like that. Yeah I'm not that familiar with opening PNG files -- thanks.
