### ISSUE TITLE
Bug when using png.Reader.palette(alpha='force') without an alpha channel.

### ISSUE THREAD

**Issue by Zoinkity** [drj11/pypng#60]
Currently using python 3.4.  There's a bug when you call the pallete(alpha='force') method of a png.Reader and the palette doesn't contain transparency info.

``  File "C:\Program Files\Python34\lib\site-packages\pypng-0.0.18-py3.4.egg\png.py", line 1973, in palette
    trns = array('B', self.trns or '')
TypeError: cannot use a str to initialize an array with typecode 'B'
``

The offending line is this one:
 ``1972:        if self.trns or alpha == 'force':
1973:             trns = array('B', self.trns or '')``

It's a fairly easy fix since you can initialize an array with an empty tuple or list:
 ``1973:           trns = array('B', self.trns or [])``

**Comment by Scondo** [comment]
Or just wrap with extra str (overridden) https://github.com/drj11/pypng/blob/master/code/png.py#L1311

https://github.com/Scondo/purepng/commit/1fab4a898a712faff20e9aa73f8062cf663c5beb

**Comment by drj11** [comment]
Fixed in f5c4c76d81093b6c3f39f83b203f6832c496c110 by borrowing Scondo's commit, referred above.
