### ISSUE TITLE
Why pass the 'info' dictionary to from_array?

### ISSUE THREAD

**Issue by troelsy** [drj11/pypng#62]
Why pass the 'info' dictionary to from_array, when it is not used directly? The only thing it does is to check, if the information is the same in array + mode compared to the dict. It would greatly simplify maintains and use of the code, if the user had to do the necessary checks.

**Comment by drj11** [comment]
probably compatibility with older code that used `info` in calls to `Writer()`.

I agree it seems like a lot of complexity.
