### ISSUE TITLE
Animated PNGs?

### ISSUE THREAD

**Issue by thquinn** [drj11/pypng#63]
Didn't find mention of this in the documentation, but is there any way to get the rows from frames of animated PNGs past the first?

**Comment by drj11** [comment]
There isn't but it probably wouldn't be hard to add.

Got a link to a specification and a few sample animated PNGs?

**Comment by Scondo** [comment]
There are two animated PNG specification: APNG and MNG , but even for simple APNG it seems to be not very easy as it require image blending and now it's not very good to join with iterator-way.

https://wiki.mozilla.org/APNG_Specification

**Comment by drj11** [comment]
no animated PNG support, as per Scondo's research.
