### ISSUE TITLE
Using write_array with bytes or bytearray objects plus the interlaced flag causes an error.

### ISSUE THREAD

**Issue by ghost** [drj11/pypng#65]
Using write_array with a bytes or bytearray object causes an error if you try to write an interlaced png.  Pixels is an array object, so slices of byte-like objects can't be assigned to it.  There's no error if interlacing isn't being used.

>   File "C:\Program Files\Python34\lib\site-packages\pypng-0.0.18-py3.4.egg\png.py", line 805, in write_array
>    self.write_passes(outfile, self.array_scanlines_interlace(pixels))
>  File "C:\Program Files\Python34\lib\site-packages\pypng-0.0.18-py3.4.egg\png.py", line 755, in write_passes
>    i,row = next(enumrows)
>  File "C:\Program Files\Python34\lib\site-packages\pypng-0.0.18-py3.4.egg\png.py", line 939, in array_scanlines_interlace
>    pixels[offset+i:end_offset:skip]
> TypeError: can only assign array (not "bytearray") to array slice

**Comment by ReallyNiceGuy** [comment]
Can you give me a small code sample that triggers the error? I use this library and I want to contribute back.

**Comment by drj11** [comment]
In Python3, a sufficient example is:

    png.Writer(interlace=True, greyscale=True, width=3, height=2).write_array(open("foo.png", 'wb'), bytes([0x55, 0xaa, 0xff, 0xaa, 0x55, 0x00]))

**Comment by drj11** [comment]
It is fair to say that `.write_array()` does not receive much attention.
