### ISSUE TITLE
Can open an image from url but not if it is download local?

### ISSUE THREAD

**Issue by zxpatric** [drj11/pypng#67]
Python 3.4 x64 on windows. pypng-0.0.18

**What I did:**
>>> f=urllib.request.urlopen('http://www.schaik.com/pngsuite/basn0g02.png')
>>> r=png.Reader(f)
>>> r.read()
(32, 32, <map object at 0x000000000341D358>, {'size': (32, 32), 'gamma': 1.0, 'a
lpha': False, 'greyscale': True, 'planes': 1, 'bitdepth': 2, 'interlace': 0})
>>> f1=open(r'e:\basn0g02.png')
>>> r1=png.Reader(f1)
>>> r1.read()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "d:\python34\lib\site-packages\png.py", line 1950, in read
    self.preamble(lenient=lenient)
  File "d:\python34\lib\site-packages\png.py", line 1740, in preamble
    self.validate_signature()
  File "d:\python34\lib\site-packages\png.py", line 1725, in validate_signature
    self.signature = self.file.read(8)
  File "d:\python34\\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 74: chara
cter maps to <undefined>

**What I saw:**
A download-to-local image is openable fine by other local application but not by the similar pypng code. Weird.    File "d:\python34\\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 74: character maps to <undefined>

**Comment by zxpatric** [comment]
Never mind.  Should do r1=png.Reader (r'e:\basn0g02.png') directly.

**Comment by Scondo** [comment]
This is a feature of Python 3.* 
`open` treats file as text by default and try to decode them to unicode
https://docs.python.org/3/library/functions.html#open
use `open(r'e:\basn0g02.png', 'b')`
