### ISSUE TITLE
pHYs information is not added to the "meta" dict

### ISSUE THREAD

**Issue by heuer** [drj11/pypng#69]
The "pHYs" chunk is read but the information is not added to the meta dict returned by `png.Reader.read()`. Users could ask the reader for the information, but IMO it should be added to the meta dict.

**Comment by drj11** [comment]
yes it should be added to the meta dict

**Comment by drj11** [comment]
closed by https://github.com/drj11/pypng/commit/0b455a13df5ebfe1564ae974bcf56288aafe81f6 and others.
