### ISSUE TITLE
GPG signatures for source validation

### ISSUE THREAD

**Issue by NicoHood** [drj11/pypng#74]
As we all know, today more than ever before, it is crucial to be able to trust our computing environments. One of the main difficulties that package maintainers of Linux distributions face, is the difficulty to verify the authenticity and the integrity of the source code.

The Arch Linux team would appreciate it if you would provide us GPG signatures in order to verify easily and quickly of your source code releases.

**Overview of the required tasks:**
* [ ] Please [create and/or use a 4096-bit RSA keypair](https://wiki.archlinux.org/index.php/GnuPG#Create_key_pair) for the file signing
* The key may be used for [email encryption](https://www.enigmail.net/index.php/en/) too
* Keep your key secret, use a strong unique passphrase for the key
* [ ] Upload the public key to a key server
* [ ] [Sign every new commit by default](https://help.github.com/articles/signing-commits-using-gpg/)
* [ ] [Sign new tags](https://help.github.com/articles/signing-tags-using-gpg/)
* Verify the Github Release tarball download against your local source
* [ ] [Sign Github Release tarballs](https://wiki.debian.org/Creating%20signed%20GitHub%20releases)

**Additional Information:**
* https://help.github.com/categories/gpg/
* https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work
* https://www.qubes-os.org/doc/verifying-signatures/
* https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https

Thanks.

**Comment by drj11** [comment]
I don't really understand.

Can't you just check that the SHA1 hash is the one that you intend to install?

**Comment by NicoHood** [comment]
Hi,
no problem, I will try my best to explain it to you.

A simple hash verification only proofs that the download was not corrupted (integrity). But what we need to securely download your software are signatures of the release tarball. This way we can verify the authenticity of the software.

Without digital signatures someone else could take over your account, the file mirror, the transmission and replace the tarball along with the hash and we wont notice that the software was modified by a third party. But if you sign the software you proof, that it was published by you and noone else. This also means, you have to keep your key and the corresponding passphrase secure.

The whole process sounds more complex than it is, just have a look at my quickstart gpg tutorial at the gpgit page. If you have further questions, feel free to ask.

**Comment by drj11** [comment]
but you have no idea who i am, and no idea how securely i keep any GPG key that i may have.
Therefore i don't think you should trust something more, just because it was signed with a GPG key.
Pick a release, fix the SHA1 checksum, audit that, and package that.

I really think it would be unwise to trust a subsequent release just because it was signed by the same GPG key as some previous release.

**Comment by NicoHood** [comment]
That is all true. But just because the threat model does not secure against every attack, doesnt mean that gpg signatures are bad. They protect against the mentioned attacks, assuming you (developer) and me (packager) want to protect against MITM attacks. And now that you understood the importance of the secret key, you are worthy to get started with GPG :)

**Comment by NicoHood** [comment]
What a shame...
