### ISSUE TITLE
the "Edit on Github" link at the top of the [documentation page](https://pypng.readthedocs.io/en/latest/) is broken!

### ISSUE THREAD

**Issue by drj11** [drj11/pypng#94]
Also, the "Edit on Github" link at the top of the [documentation page](https://pypng.readthedocs.io/en/latest/) is broken! I'm not sure where to look to fix that...

_Originally posted by @vck3000 in https://github.com/drj11/pypng/pull/93#issuecomment-517092793_

**Comment by drj11** [comment]
The link should be to https://github.com/drj11/pypng/blob/main/man/index.rst

The broken link has `origin/main` instead of `main`. Suggesting some sort of wrong branch problem: using the branch `origin/main` instead of `main`.

**Comment by drj11** [comment]
it appears to work now, but I have no idea why.

**Comment by vck3000** [comment]
Haha no worries. Glad it's working.
