### ISSUE TITLE
from_array to accept 3D-arrays

### ISSUE THREAD

**Issue by guischseequent** [drj11/pypng#95]
the only change would take I think, is: 
```
if a.ndim == 3:
    a = a.reshape((a.shape[0], -1))
```
somewhere in `from_array()`, before grabbing the first row in a
Cheers

**Comment by drj11** [comment]
This is an excellent workaround. And I will add it to the documentation.

I previously removed support for 3D arrays.

Are there any circumstance where someone who is using `from_array()` does not know ahead of time if they have a 2D or a 3D array?

**Comment by guischseequent** [comment]
I suppose one would always know (or if not test it).
This issue is more a user-friendliness feature.
As far as I am concerned t is very common and convenient to carry around (h,w,c) arrays in matplotlib or similar python-matrix libraries. Having from_array accept those directly is extra sugar that avoids having to think too much how the heck the reshaping works ;)

**Comment by drj11** [comment]
The documentation already has a note about `reshape`: https://pypng.readthedocs.io/en/latest/ex.html#numpy-array-to-png-writing
