### ISSUE TITLE
png raw data rather than save to file

### ISSUE THREAD

**Issue by BeijingUncle** [drj11/pypng#96]
How can I get the png raw data convert from an array?
Then I can base64 it for future use.

Thanks a lot.

**Comment by silverbacknet** [comment]
```
import png, base64
raw = b''
png.Writer(x, y).write(raw)
result = b64encode(raw)
```

There are many ways you can use the library, but it's easy to get the output.

**Comment by BeijingUncle** [comment]
thank you！
