### ISSUE TITLE
In the documentation, "A ramp" example is broken on the live site

### ISSUE THREAD

**Issue by shawwn** [drj11/pypng#97]
In [PyPNG Code Examples](https://pythonhosted.org/pypng/ex.html) as of Jan 14 2020, the first example looks like this:

```py
import png
f = open('ramp.png', 'wb')      # binary mode is important
w = png.Writer(255, 1, greyscale=True)
w.write(f, [range(256)])
f.close()
```

Screenshot:

![image](https://user-images.githubusercontent.com/59632/72329934-45507700-367b-11ea-8ee4-b7362526fa3f.png)

However, this example is wrong. `png.Writer` should get `256` as it first argument, but this example passes in `255`. The resulting error was hard to understand:

```
>>> w.write(f, [range(256)])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/png.py", line 670, in write
    nrows = self.write_passes(outfile, check_rows(rows))
  File "/usr/local/lib/python3.7/site-packages/png.py", line 704, in write_passes
    return self.write_packed(outfile, rows)
  File "/usr/local/lib/python3.7/site-packages/png.py", line 736, in write_packed
    for i, row in enumerate(rows):
  File "/usr/local/lib/python3.7/site-packages/png.py", line 662, in check_rows
    (vpr, len(row), i))
png.ProtocolError: ProtocolError: Expected 255 values but got 256 value, in row 0
```

However, when I tried to submit a fix to the documentation, it's apparently already fixed!

https://github.com/drj11/pypng/blob/b4d31df682522ffcb9834aa9a1bcae95ac30bd14/man/ex.rst#a-ramp

So I suspect that the live version of https://pythonhosted.org/pypng/ex.html is out of date. Would it be possible to rebuild and redeploy it?

**Comment by drj11** [comment]
I'm sorry that the error was hard to understand and that you found the out of date documentation.

The short answer is No.
pythonhosted.org is no longer maintained (you can't upload new documentation), and I should delete that documentation.

Some more details on pythonhosted.org here: https://github.com/pypa/pypi-legacy/issues/700

**Comment by drj11** [comment]
I have now deleted that out of date documentation on pythonhosted. Thanks for bringing this to my attention.

The current documentation is on readthedocs by the way: https://pypng.readthedocs.io/en/latest/ex.html
